export enum ErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',

  // Users
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PIN = 'INVALID_PIN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Families
  FAMILY_NOT_FOUND = 'FAMILY_NOT_FOUND',
  FAMILY_MEMBER_NOT_FOUND = 'FAMILY_MEMBER_NOT_FOUND',
  FAMILY_MEMBER_ALREADY_EXISTS = 'FAMILY_MEMBER_ALREADY_EXISTS',

  // Children
  CHILD_NOT_FOUND = 'CHILD_NOT_FOUND',

  // Tasks
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_NOT_ALLOWED = 'TASK_NOT_ALLOWED',
  TASK_INVALID_STATUS = 'TASK_INVALID_STATUS',
  TASK_ASSIGNMENT_NOT_FOUND = 'TASK_ASSIGNMENT_NOT_FOUND',
  TASK_ALREADY_EXISTS = 'TASK_ALREADY_EXISTS',

  // Rewards
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  REWARD_NOT_ALLOWED = 'REWARD_NOT_ALLOWED',
  REWARD_INACTIVE = 'REWARD_INACTIVE',
  REWARD_INSUFFICIENT_BALANCE = 'REWARD_INSUFFICIENT_BALANCE',
  REWARD_REDEMPTION_NOT_FOUND = 'REWARD_REDEMPTION_NOT_FOUND',
  REWARD_REDEMPTION_INVALID_STATUS = 'REWARD_REDEMPTION_INVALID_STATUS',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // Validation — field constraints
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED',
  VALIDATION_MIN_LENGTH = 'VALIDATION_MIN_LENGTH',
  VALIDATION_MAX_LENGTH = 'VALIDATION_MAX_LENGTH',
  VALIDATION_STRING = 'VALIDATION_STRING',
  VALIDATION_EMAIL = 'VALIDATION_EMAIL',
  VALIDATION_PIN_FORMAT = 'VALIDATION_PIN_FORMAT',
  VALIDATION_FORMAT = 'VALIDATION_FORMAT',
  VALIDATION_ENUM = 'VALIDATION_ENUM',
  VALIDATION_NUMBER = 'VALIDATION_NUMBER',
  VALIDATION_INTEGER = 'VALIDATION_INTEGER',
  VALIDATION_MIN = 'VALIDATION_MIN',
  VALIDATION_MAX = 'VALIDATION_MAX',
  VALIDATION_DATE = 'VALIDATION_DATE',
  VALIDATION_BOOLEAN = 'VALIDATION_BOOLEAN',
  VALIDATION_ARRAY = 'VALIDATION_ARRAY',
  VALIDATION_UUID = 'VALIDATION_UUID',
  VALIDATION_IN = 'VALIDATION_IN',
  VALIDATION_UNKNOWN_FIELD = 'VALIDATION_UNKNOWN_FIELD',
  VALIDATION_INVALID = 'VALIDATION_INVALID',

  // Validation — business rules
  VALIDATION_EMAIL_REQUIRED = 'VALIDATION_EMAIL_REQUIRED',
  VALIDATION_USERNAME_REQUIRED = 'VALIDATION_USERNAME_REQUIRED',
  VALIDATION_ADMIN_EMAIL_ONLY = 'VALIDATION_ADMIN_EMAIL_ONLY',
  VALIDATION_USERNAME_ONLY = 'VALIDATION_USERNAME_ONLY',
  VALIDATION_PIN_REQUIRED_WITH_USERNAME = 'VALIDATION_PIN_REQUIRED_WITH_USERNAME',
  VALIDATION_USERNAME_REQUIRED_WITH_PIN = 'VALIDATION_USERNAME_REQUIRED_WITH_PIN',
  VALIDATION_FAMILY_ID_REQUIRED = 'VALIDATION_FAMILY_ID_REQUIRED',
  VALIDATION_LOGIN_IDENTIFIER_REQUIRED = 'VALIDATION_LOGIN_IDENTIFIER_REQUIRED',
  VALIDATION_LOGIN_IDENTIFIER_EXCLUSIVE = 'VALIDATION_LOGIN_IDENTIFIER_EXCLUSIVE',
  VALIDATION_FILE_REQUIRED = 'VALIDATION_FILE_REQUIRED',
  VALIDATION_FILE_TOO_LARGE = 'VALIDATION_FILE_TOO_LARGE',
  VALIDATION_FILE_TYPE_NOT_ALLOWED = 'VALIDATION_FILE_TYPE_NOT_ALLOWED',
}