export enum ErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  // Users
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PIN = 'INVALID_PIN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Families
  FAMILY_NOT_FOUND = 'FAMILY_NOT_FOUND',
  FAMILY_MEMBER_NOT_FOUND = 'FAMILY_MEMBER_NOT_FOUND',

  // Invitations
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED',
}