export enum ErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',

  // Users
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_PIN = 'INVALID_PIN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Families
  FAMILY_NOT_FOUND = 'FAMILY_NOT_FOUND',
  FAMILY_MEMBER_NOT_FOUND = 'FAMILY_MEMBER_NOT_FOUND',
  FAMILY_MEMBER_ALREADY_EXISTS = 'FAMILY_MEMBER_ALREADY_EXISTS',

  // Children
  CHILD_NOT_FOUND = 'CHILD_NOT_FOUND',

  // Tasks
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_NOT_ALLOWED = 'TASK_NOT_ALLOWED',
  TASK_INVALID_STATUS = 'TASK_INVALID_STATUS',

  // Rewards
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  REWARD_NOT_ALLOWED = 'REWARD_NOT_ALLOWED',
  REWARD_INACTIVE = 'REWARD_INACTIVE',
  REWARD_INSUFFICIENT_BALANCE = 'REWARD_INSUFFICIENT_BALANCE',
  REWARD_REDEMPTION_NOT_FOUND = 'REWARD_REDEMPTION_NOT_FOUND',
  REWARD_REDEMPTION_INVALID_STATUS = 'REWARD_REDEMPTION_INVALID_STATUS',

  // Invitations
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_ALREADY_REJECTED = 'INVITATION_ALREADY_REJECTED',
  INVITATION_ALREADY_EXISTS = 'INVITATION_ALREADY_EXISTS',
  INVITATION_NOT_ALLOWED = 'INVITATION_NOT_ALLOWED',
  INVITATION_SELF_INVITE = 'INVITATION_SELF_INVITE',
}