export const JWT_ACCESS_EXPIRES_IN = '15m';
export const REFRESH_TOKEN_EXPIRES_IN_DAYS = 30;
export const REFRESH_TOKEN_BYTES = 32;
export const PASSWORD_RESET_CODE_EXPIRES_IN_MINUTES = 15;
export const PASSWORD_RESET_MAX_ATTEMPTS = 5;
export const PASSWORD_RESET_CODE_LENGTH = 6;